### ISSUE TITLE
[Bug]: Crash when open Origins

### ISSUE THREAD

**Issue by ElectroSeelie** [Suiranoil/SkinRestorer#63]
### SkinRestorer Version

2.4.2

### Minecraft Version

1.20.1

### Mod Loader & Version

Forge 47.4.3

### Java Version

8

### Bug Description

crash when open origin tab, either by pressing it normally or using orb of origins, not sure about world start
I also test it in my own world (we play LAN), seems like it only crash other player who do it, not the host

### Reproduction Steps

1. Install both Skin Restorer and Origins
2. Press open Origin tab

### Relevant Logs

```shell
-- Head --
Thread: Render thread
Suspected Mods: 
	Origins (origins), Version: 1.20.1-1.10.0.9
		Issue tracker URL: https://github.com/EdwinMindcraft/origins-architectury/issues
		at TRANSFORMER/origins@1.20.1-1.10.0.9/io.github.apace100.origins.screen.OriginDisplayScreen.renderOriginName(OriginDisplayScreen.java:255)

	SkinRestorer (skinrestorer), Version: 2.4.2+1.20-forge
		Issue tracker URL: https://github.com/Suiranoil/SkinRestorer/issues
		Mixin class: net.lionarius.skinrestorer.mixin.SkullBlockEntityMixin
		Target: net.minecraft.world.level.block.entity.SkullBlockEntity
		at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.entity.SkullBlockEntity.skinrestorer$replaceSkin(SkullBlockEntity.java:545)
Stacktrace:
	at net.minecraft.world.level.block.entity.SkullBlockEntity.skinrestorer$replaceSkin(SkullBlockEntity.java:545) ~[client-1.20.1-20230612.114412-srg.jar%23410!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:skinrestorer.mixins.json:SkullBlockEntityMixin from mod skinrestorer,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.level.block.entity.SkullBlockEntity.handler$dng000$skinrestorer$fetchProfileByName(SkullBlockEntity.java:535) ~[client-1.20.1-20230612.114412-srg.jar%23410!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:skinrestorer.mixins.json:SkullBlockEntityMixin from mod skinrestorer,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.level.block.entity.SkullBlockEntity.m_155738_(SkullBlockEntity.java) ~[client-1.20.1-20230612.114412-srg.jar%23410!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:skinrestorer.mixins.json:SkullBlockEntityMixin from mod skinrestorer,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.client.renderer.BlockEntityWithoutLevelRenderer.m_108829_(BlockEntityWithoutLevelRenderer.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23410!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115143_(ItemRenderer.java:151) ~[client-1.20.1-20230612.114412-srg.jar%23410!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-renderer-indigo.mixins.json:ItemRendererMixin from mod fabric_renderer_indigo,pl:mixin:APP:fabric-resource-loader-v0.client.mixins.json:KeyedResourceReloadListenerClientMixin from mod fabric_resource_loader_v0,pl:mixin:APP:embeddium.mixins.json:features.render.model.item.ItemRendererMixin from mod embeddium,pl:mixin:APP:mixins.oculus.json:entity_render_context.MixinItemRenderer from mod oculus,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.GuiGraphics.m_280405_(GuiGraphics.java:483) ~[client-1.20.1-20230612.114412-srg.jar%23410!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.GuiGraphics.m_280053_(GuiGraphics.java:466) ~[client-1.20.1-20230612.114412-srg.jar%23410!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.GuiGraphics.m_280480_(GuiGraphics.java:446) ~[client-1.20.1-20230612.114412-srg.jar%23410!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at io.github.apace100.origins.screen.OriginDisplayScreen.renderOriginName(OriginDisplayScreen.java:255) ~[origins-forge-1.20.1-1.10.0.9-all.jar%23376!/:1.20.1-1.10.0.9] {re:classloading}
	at io.github.apace100.origins.screen.OriginDisplayScreen.renderOriginWindow(OriginDisplayScreen.java:223) ~[origins-forge-1.20.1-1.10.0.9-all.jar%23376!/:1.20.1-1.10.0.9] {re:classloading}
	at io.github.apace100.origins.screen.OriginDisplayScreen.m_88315_(OriginDisplayScreen.java:123) ~[origins-forge-1.20.1-1.10.0.9-all.jar%23376!/:1.20.1-1.10.0.9] {re:classloading}
	at io.github.apace100.origins.screen.ViewOriginScreen.m_88315_(ViewOriginScreen.java:104) ~[origins-forge-1.20.1-1.10.0.9-all.jar%23376!/:1.20.1-1.10.0.9] {re:classloading}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23410!/:?] {re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-screen-api-v1.mixins.json:ScreenMixin from mod fabric_screen_api_v1,pl:mixin:APP:balm.mixins.json:ScreenAccessor from mod balm,pl:mixin:APP:fabric-screen-api-v1.mixins.json:ScreenAccessor from mod fabric_screen_api_v1,pl:mixin:APP:dynamic_fps-common.mixins.json:ScreenMixin from mod dynamic_fps,pl:mixin:APP:controlling.mixins.json:AccessScreen from mod controlling,pl:mixin:APP:konkrete.mixin.json:IMixinScreen from mod konkrete,pl:mixin:APP:trender.mixins.json:client.ScreenAccessor from mod trender,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:428) ~[forge-1.20.1-47.4.3-universal.jar%23415!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:421) ~[forge-1.20.1-47.4.3-universal.jar%23415!/:?] {re:mixin,re:classloading,pl:mixin:A}
-- Item being rendered --
Details:
	Item Type: player_head
	Registry Name: minecraft:player_head
	Item Damage: 0
	Item NBT: {}
	Item Foil: false
Stacktrace:
	at net.minecraft.client.gui.GuiGraphics.m_280405_(GuiGraphics.java:483) ~[client-1.20.1-20230612.114412-srg.jar%23410!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.GuiGraphics.m_280053_(GuiGraphics.java:466) ~[client-1.20.1-20230612.114412-srg.jar%23410!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.GuiGraphics.m_280480_(GuiGraphics.java:446) ~[client-1.20.1-20230612.114412-srg.jar%23410!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at io.github.apace100.origins.screen.OriginDisplayScreen.renderOriginName(OriginDisplayScreen.java:255) ~[origins-forge-1.20.1-1.10.0.9-all.jar%23376!/:1.20.1-1.10.0.9] {re:classloading}
	at io.github.apace100.origins.screen.OriginDisplayScreen.renderOriginWindow(OriginDisplayScreen.java:223) ~[origins-forge-1.20.1-1.10.0.9-all.jar%23376!/:1.20.1-1.10.0.9] {re:classloading}
	at io.github.apace100.origins.screen.OriginDisplayScreen.m_88315_(OriginDisplayScreen.java:123) ~[origins-forge-1.20.1-1.10.0.9-all.jar%23376!/:1.20.1-1.10.0.9] {re:classloading}
	at io.github.apace100.origins.screen.ViewOriginScreen.m_88315_(ViewOriginScreen.java:104) ~[origins-forge-1.20.1-1.10.0.9-all.jar%23376!/:1.20.1-1.10.0.9] {re:classloading}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23410!/:?] {re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-screen-api-v1.mixins.json:ScreenMixin from mod fabric_screen_api_v1,pl:mixin:APP:balm.mixins.json:ScreenAccessor from mod balm,pl:mixin:APP:fabric-screen-api-v1.mixins.json:ScreenAccessor from mod fabric_screen_api_v1,pl:mixin:APP:dynamic_fps-common.mixins.json:ScreenMixin from mod dynamic_fps,pl:mixin:APP:controlling.mixins.json:AccessScreen from mod controlling,pl:mixin:APP:konkrete.mixin.json:IMixinScreen from mod konkrete,pl:mixin:APP:trender.mixins.json:client.ScreenAccessor from mod trender,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:428) ~[forge-1.20.1-47.4.3-universal.jar%23415!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:421) ~[forge-1.20.1-47.4.3-universal.jar%23415!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23410!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apoli.mixins.json:GameRendererMixin from mod apoli,pl:mixin:APP:dynamic_fps-common.mixins.json:GameRendererMixin from mod dynamic_fps,pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer from mod immediatelyfast,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing from mod oculus,pl:mixin:APP:justzoom.mixins.json:client.MixinGameRenderer from mod justzoom,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod embeddium,pl:mixin:APP:mixins.tweakeroo.json:MixinGameRenderer from mod tweakeroo,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat from mod oculus,pl:mixin:APP:forge-badoptimizations.mixins.json:accessors.GameRendererAccessor from mod (unknown),pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinGameRenderer from mod (unknown),pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23410!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:APP:mixins.tweakeroo.json:MixinMinecraftClient from mod tweakeroo,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin from mod apoli,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:fabric-screen-api-v1.mixins.json:MinecraftClientMixin from mod fabric_screen_api_v1,pl:mixin:APP:transition.mixins.json:EntityRenderStateMixin from mod transition,pl:mixin:APP:transition.mixins.json:EntityRendererMixin from mod transition,pl:mixin:APP:dynamic_fps-common.mixins.json:MinecraftMixin from mod dynamic_fps,pl:mixin:APP:fabric-registry-sync-v0.client.mixins.json:MinecraftClientMixin from mod fabric_registry_sync_v0,pl:mixin:APP:immediatelyfast-common.mixins.json:core.MixinMinecraftClient from mod immediatelyfast,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement from mod oculus,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft from mod bookshelf,pl:mixin:APP:carryon.mixins.json:MinecraftMixin from mod carryon,pl:mixin:APP:mixins.sodiumdynamiclights.json:MinecraftClientMixin from mod sodiumdynamiclights,pl:mixin:APP:konkrete.mixin.json:MixinMinecraft from mod konkrete,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftMixin from mod connectormod,pl:mixin:APP:mixins.malilib.json:MixinMinecraftClient from mod malilib,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:offhandcombat-common.mixins.json:ClickMixin from mod offhandcombat,pl:mixin:APP:offhandcombat.mixins.json:RightClickMixin from mod offhandcombat,pl:mixin:APP:fabric-networking-api-v1.client.mixins.json:accessor.MinecraftClientAccessor from mod fabric_networking_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:MinecraftClientMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:mixins.irons_spellbooks.json:MinecraftMixin from mod irons_spellbooks,pl:mixin:APP:fabric-events-interaction-v0.client.mixins.json:MinecraftClientMixin from mod fabric_events_interaction_v0,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor from mod embeddium,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:APP:modernfix-common.mixins.json:feature.remove_telemetry.MinecraftMixin_Telemetry from mod modernfix,pl:mixin:APP:connectormod.mixins.json:boot.MinecraftMixin from mod connectormod,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23410!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:APP:mixins.tweakeroo.json:MixinMinecraftClient from mod tweakeroo,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin from mod apoli,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:fabric-screen-api-v1.mixins.json:MinecraftClientMixin from mod fabric_screen_api_v1,pl:mixin:APP:transition.mixins.json:EntityRenderStateMixin from mod transition,pl:mixin:APP:transition.mixins.json:EntityRendererMixin from mod transition,pl:mixin:APP:dynamic_fps-common.mixins.json:MinecraftMixin from mod dynamic_fps,pl:mixin:APP:fabric-registry-sync-v0.client.mixins.json:MinecraftClientMixin from mod fabric_registry_sync_v0,pl:mixin:APP:immediatelyfast-common.mixins.json:core.MixinMinecraftClient from mod immediatelyfast,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement from mod oculus,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft from mod bookshelf,pl:mixin:APP:carryon.mixins.json:MinecraftMixin from mod carryon,pl:mixin:APP:mixins.sodiumdynamiclights.json:MinecraftClientMixin from mod sodiumdynamiclights,pl:mixin:APP:konkrete.mixin.json:MixinMinecraft from mod konkrete,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftMixin from mod connectormod,pl:mixin:APP:mixins.malilib.json:MixinMinecraftClient from mod malilib,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:offhandcombat-common.mixins.json:ClickMixin from mod offhandcombat,pl:mixin:APP:offhandcombat.mixins.json:RightClickMixin from mod offhandcombat,pl:mixin:APP:fabric-networking-api-v1.client.mixins.json:accessor.MinecraftClientAccessor from mod fabric_networking_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:MinecraftClientMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:mixins.irons_spellbooks.json:MinecraftMixin from mod irons_spellbooks,pl:mixin:APP:fabric-events-interaction-v0.client.mixins.json:MinecraftClientMixin from mod fabric_events_interaction_v0,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor from mod embeddium,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:APP:modernfix-common.mixins.json:feature.remove_telemetry.MinecraftMixin_Telemetry from mod modernfix,pl:mixin:APP:connectormod.mixins.json:boot.MinecraftMixin from mod connectormod,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.4.3.jar:?] {re:classloading,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.4.3.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.4.3.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.4.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
```

### Confirmations

- [x] I've checked for existing issues
- [x] This bug is reproducible consistently
- [x] I've tested without other mods

**Comment by InvalidArgument3** [comment]
seems to be something with the player head preview on the origins. downgrading the mod to 2.3.5 avoids this issue, so it was probably something in the update that added player skull support

https://modrinth.com/mod/skinrestorer/version/2.4.0+1.20-forge

**Comment by Suiranoil** [comment]
Yeah, the best solution for now would be to downgrade to 2.3.5 or uninstall mod from your client and keep it only on the server (if you use dedicated server).

I identified the source of the issue and it will be fixed in next version.

**Comment by Suiranoil** [comment]
should be fixed in 2.4.3

**Comment by ChangeOtaku** [comment]
i think this is still happening
[crash-2026-04-06_22.59.08-client.txt](https://github.com/user-attachments/files/26523834/crash-2026-04-06_22.59.08-client.txt)

**Comment by MaskedKing859** [comment]
Haveing same issue

**Comment by qokifu** [comment]
i ran into this exact same crash! **downgrading SkinRestorer to an older version (2.0.3)** (both client and server) fixed it for me, my guess is that that version predates the mixin thats causing the crash, so it skips the SkullBlockEntity skin-replace logic that's breaking on the Origins character select screen's player head.

it's not really a fix, but a workaround if anyone else is stuck.

**Comment by Suiranoil** [comment]
This will be fixed in the next version. I made a mistake when I was backporting to versions 1.20.1 and older

**Comment by Suiranoil** [comment]
Should be fixed in 2.11.0
